/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package aplikasi.surat.desa;

import aplikasi.surat.desa.datapenduduk.Koneksi;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author WINDY PERMADI
 */
public class FrameSuratKematian extends javax.swing.JFrame {
    SimpleDateFormat sdf;
    private DefaultTableModel DftTblModel_data;
    private String SQL; 
    String nik, nama, jk, tgllahir, tempatlahir, agama, pekerjaan,alamat, desa, kelurahan, kecamatan; 
    String nikAyah, namaAyah, jkAyah, tgllahirAyah, tempatlahirAyah, agamaAyah, pekerjaanAyah,alamatAyah, desaAyah, kelurahanAyah, kecamatanAyah; 
    String nikIbu, namaIbu, jkIbu, tgllahirIbu, tempatlahirIbu, agamaIbu, pekerjaanIbu,alamatIbu, desaIbu, kelurahanIbu, kecamatanIbu; 
    String nikPelapor, namaPelapor, jkPelapor, tgllahirPelapor, tempatlahirPelapor, agamaPelapor, pekerjaanPelapor, alamatPelapor, desaPelapor, kelurahanPelapor, kecamatanPelapor; 
    String nikSaksi, namaSaksi, jkSaksi, tgllahirSaksi, tempatlahirSaksi, agamaSaksi, pekerjaanSaksi, alamatSaksi, desaSaksi, kelurahanSaksi, kecamatanSaksi; 

    /**
     * Creates new form FrameSuratKematian2
     */
    public FrameSuratKematian() {
        initComponents();
        this.TampilDataJenazah();
        this.TampilDataAyah();
        this.TampilDataIbu();
        this.TampilDataPelapor();
        this.TampilDataSaksi();
            labelJenazah.setVisible(false);
            labelAyah.setVisible(false);
            labelIbu.setVisible(false);
            labelPelapor.setVisible(false);
            labelSaksi.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtNamaKK = new javax.swing.JTextField();
        txtNomorKK = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtNikJenazah = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableJenazah = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        txtAnak = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtPukul = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtTempat = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        txtSebab = new javax.swing.JComboBox<>();
        txtMenerangkan = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txtNikAyah = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableAyah = new javax.swing.JTable();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txtNikIbu = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTableIbu = new javax.swing.JTable();
        txtNikPelapor = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTablePelapor = new javax.swing.JTable();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        txtNikSaksi = new javax.swing.JTextField();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTableSaksi = new javax.swing.JTable();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        btnSimpan = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        labelAyah = new javax.swing.JLabel();
        labelJenazah = new javax.swing.JLabel();
        labelIbu = new javax.swing.JLabel();
        labelPelapor = new javax.swing.JLabel();
        labelSaksi = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        txtTanggal = new com.toedter.calendar.JDateChooser();

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel5.setText("Identitas Jenazah");
        jLabel5.setAlignmentY(0.0F);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Surat Keterangan Kematian");

        txtNamaKK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNamaKKActionPerformed(evt);
            }
        });

        txtNomorKK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomorKKActionPerformed(evt);
            }
        });

        jLabel2.setText("Nama Kepala Keluarga");

        jLabel3.setText("Nomor Kepala Keluarga");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Identitas Jenazah");
        jLabel6.setAlignmentY(0.0F);

        jLabel7.setText("NIK");

        txtNikJenazah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNikJenazahActionPerformed(evt);
            }
        });
        txtNikJenazah.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNikJenazahKeyReleased(evt);
            }
        });

        jTableJenazah.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTableJenazah.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableJenazahMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableJenazah);

        jLabel8.setText("Tanggal Kematian");

        txtAnak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAnakActionPerformed(evt);
            }
        });

        jLabel9.setText("Pukul Kematian");

        txtPukul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPukulActionPerformed(evt);
            }
        });

        jLabel11.setText("Yang Menerangkan");

        txtTempat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTempatActionPerformed(evt);
            }
        });

        jLabel10.setText("Sebab kematian");

        jLabel12.setText("Tempat Kematian");

        jLabel22.setText("Anak ke");

        txtSebab.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sakit biasa/tua", "Wabah penyakit", "Kecelakaan", "Kriminalitas", "Bunuh diri", "Lainnya", " " }));

        txtMenerangkan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Dokter", "Tenaga Kesehatan", "Kepolisian", "Lainnya" }));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel13.setText("Identitas Ayah");
        jLabel13.setAlignmentY(0.0F);

        jLabel14.setText("NIK");

        txtNikAyah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNikAyahActionPerformed(evt);
            }
        });
        txtNikAyah.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNikAyahKeyReleased(evt);
            }
        });

        jTableAyah.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTableAyah.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableAyahMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTableAyah);

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel15.setText("Identitas Ibu");
        jLabel15.setAlignmentY(0.0F);

        jLabel16.setText("NIK");

        txtNikIbu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNikIbuActionPerformed(evt);
            }
        });
        txtNikIbu.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNikIbuKeyReleased(evt);
            }
        });

        jTableIbu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTableIbu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableIbuMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jTableIbu);

        txtNikPelapor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNikPelaporActionPerformed(evt);
            }
        });
        txtNikPelapor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNikPelaporKeyReleased(evt);
            }
        });

        jTablePelapor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTablePelapor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTablePelaporMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(jTablePelapor);

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel17.setText("Identitas Pelapor");
        jLabel17.setAlignmentY(0.0F);

        jLabel18.setText("NIK");

        txtNikSaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNikSaksiActionPerformed(evt);
            }
        });
        txtNikSaksi.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNikSaksiKeyReleased(evt);
            }
        });

        jTableSaksi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTableSaksi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableSaksiMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(jTableSaksi);

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel19.setText("Identitas Saksi I");
        jLabel19.setAlignmentY(0.0F);

        jLabel20.setText("NIK");

        btnSimpan.setText("Simpan Data");
        btnSimpan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSimpanMouseClicked(evt);
            }
        });
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });

        jButton3.setText("Export Surat");

        labelAyah.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        labelAyah.setText("Identitas Ayah Sudah Dipilih");

        labelJenazah.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        labelJenazah.setText("Identitas Jenazah Sudah Dipilih");

        labelIbu.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        labelIbu.setText("Identitas Ibu Sudah Dipilih");

        labelPelapor.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        labelPelapor.setText("Identitas Pelapor Sudah Dipilih");

        labelSaksi.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        labelSaksi.setText("Identitas Saksi Sudah Dipilih");

        jButton1.setText("Kembali");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(501, 501, 501))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtNikJenazah, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtNamaKK, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(51, 51, 51)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtNomorKK, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(labelJenazah))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel22)
                            .addComponent(jLabel9)
                            .addComponent(jLabel8))
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtPukul, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                            .addComponent(txtAnak)
                            .addComponent(txtTanggal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel12)
                            .addComponent(jLabel11))
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtSebab, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtMenerangkan, 0, 163, Short.MAX_VALUE)
                            .addComponent(txtTempat)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 561, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel20)
                        .addGap(123, 123, 123)
                        .addComponent(txtNikSaksi, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(labelSaksi))
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 561, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addGap(123, 123, 123)
                        .addComponent(txtNikAyah, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(labelAyah))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 561, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addGap(123, 123, 123)
                        .addComponent(txtNikIbu, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(labelIbu))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 561, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel18)
                        .addGap(123, 123, 123)
                        .addComponent(txtNikPelapor, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(labelPelapor))
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 561, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(18, 18, 18)
                        .addComponent(jButton3)
                        .addGap(18, 18, 18)
                        .addComponent(btnSimpan)))
                .addGap(14, 14, 14))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(txtNamaKK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNomorKK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jLabel13))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txtNikJenazah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14)
                            .addComponent(txtNikAyah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelJenazah))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelAyah)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtAnak, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel22))
                                .addGap(13, 13, 13)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(txtTanggal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(14, 14, 14)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel9)
                                    .addComponent(txtPukul, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel10)
                                    .addComponent(txtSebab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel12)
                                    .addComponent(txtTempat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(16, 16, 16)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11)
                                    .addComponent(txtMenerangkan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel19)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel20)
                                    .addComponent(txtNikSaksi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(labelSaksi))
                                .addGap(96, 96, 96))
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel16)
                                    .addComponent(txtNikIbu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(labelIbu))
                                .addGap(96, 96, 96))
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel18)
                            .addComponent(txtNikPelapor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelPelapor))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSimpan)
                    .addComponent(jButton3)
                    .addComponent(jButton1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowActivated

    private void txtNamaKKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNamaKKActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNamaKKActionPerformed

    private void txtNomorKKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomorKKActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomorKKActionPerformed

    private void txtNikJenazahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNikJenazahActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNikJenazahActionPerformed

    private void txtAnakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAnakActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAnakActionPerformed

    private void txtPukulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPukulActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPukulActionPerformed

    private void txtTempatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTempatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTempatActionPerformed

    private void txtNikAyahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNikAyahActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNikAyahActionPerformed

    private void txtNikIbuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNikIbuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNikIbuActionPerformed

    private void txtNikPelaporActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNikPelaporActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNikPelaporActionPerformed

    private void txtNikSaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNikSaksiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNikSaksiActionPerformed

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        // TODO add your handling code here:
        try {
            int pilsebab=0, pilmenerangkan = 0;
            String ssebab="", smenerangkan="";
            
            pilsebab = txtSebab.getSelectedIndex();
            if (pilsebab==0) { ssebab="Sakit biasa/tua";}
            if (pilsebab==1) { ssebab="Wabah penyakit";}
            if (pilsebab==2) { ssebab="Kecelakaan";}
            if (pilsebab==3) { ssebab="Kriminalitas";}
            if (pilsebab==4) { ssebab="Bunuh diri";}
            if (pilsebab==5) { ssebab="Lainnya";}
            
            sdf = new SimpleDateFormat("yyyy-M-d");

            pilmenerangkan = txtMenerangkan.getSelectedIndex();
            if (pilmenerangkan==0) { smenerangkan="Dokter";}
            if (pilmenerangkan==1) { smenerangkan="Tenaga Kesehatan";}
            if (pilmenerangkan==2) { smenerangkan="Kepolisian";}
            if (pilmenerangkan==3) { smenerangkan="Lainnya";}
            
            Connection conn = Koneksi.getConnection();
            PreparedStatement stmt = conn.prepareStatement("INSERT INTO surat_kematian(nama_kk, nomor_kk, fk_penduduk, anak_ke, keterangan, "
 + "tempat_kematian, waktu_kematian, tgl_kematian, ket_penerangan_kematian, fk_ayah, fk_ibu, fk_pelapor, fk_saksi1) values(?,?,"
 + "?,?,?,?,?,?,?,?,?,?,?)");
            stmt.setString(1, txtNamaKK.getText());
            stmt.setString(2, txtNomorKK.getText());
            stmt.setString(3, txtNikJenazah.getText());
            stmt.setString(4, txtAnak.getText());
            stmt.setString(5, ssebab);
            stmt.setString(6, txtTempat.getText());
            stmt.setString(7, txtPukul.getText());
            stmt.setString(8, sdf.format(txtTanggal.getDate()));
            stmt.setString(9, smenerangkan);
            stmt.setString(10, txtNikAyah.getText());
            stmt.setString(11, txtNikIbu.getText());
            stmt.setString(12, txtNikPelapor.getText());
            stmt.setString(13, txtNikSaksi.getText());
            stmt.executeUpdate();
            JOptionPane.showMessageDialog(null, "Data berhasil disimpan", "Pesan", JOptionPane.INFORMATION_MESSAGE);
//            TampilData();
        } catch (SQLException e) {
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void txtNikJenazahKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNikJenazahKeyReleased
        // TODO add your handling code here:
        String key = txtNikJenazah.getText();
        System.out.println(key);
        if(key!=""){
            cariDataJenazah(key);
        }else{
            TampilDataJenazah();
        }
    }//GEN-LAST:event_txtNikJenazahKeyReleased

    private void jTableJenazahMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableJenazahMouseClicked
        // TODO add your handling code here:
        int baris = jTableJenazah.rowAtPoint(evt.getPoint());
        String nik2 = jTableJenazah.getValueAt(baris, 0).toString();
        txtNikJenazah.setText(nik2);
        nik = jTableJenazah.getValueAt(baris, 0).toString();
        nama = jTableJenazah.getValueAt(baris,1).toString();
        jk = jTableJenazah.getValueAt(baris,2).toString();
        tgllahir = jTableJenazah.getValueAt(baris,3).toString();
        tempatlahir = jTableJenazah.getValueAt(baris,4).toString();
        agama = jTableJenazah.getValueAt(baris,5).toString();
        pekerjaan = jTableJenazah.getValueAt(baris,6).toString();
        alamat = jTableJenazah.getValueAt(baris,7).toString();
        desa = jTableJenazah.getValueAt(baris,8).toString();
        kelurahan = jTableJenazah.getValueAt(baris,9).toString();
        kecamatan = jTableJenazah.getValueAt(baris,10).toString();

        labelJenazah.setVisible(true);
    }//GEN-LAST:event_jTableJenazahMouseClicked

    private void jTableAyahMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableAyahMouseClicked
        // TODO add your handling code here:
        int baris = jTableAyah.rowAtPoint(evt.getPoint());
        String nik2 = jTableJenazah.getValueAt(baris, 0).toString();
        txtNikAyah.setText(nik2);
        nikAyah = jTableAyah.getValueAt(baris, 0).toString();
        namaAyah = jTableAyah.getValueAt(baris,1).toString();
        jkAyah = jTableAyah.getValueAt(baris,2).toString();
        tgllahirAyah = jTableAyah.getValueAt(baris,3).toString();
        tempatlahirAyah = jTableAyah.getValueAt(baris,4).toString();
        agamaAyah = jTableAyah.getValueAt(baris,5).toString();
        pekerjaanAyah = jTableAyah.getValueAt(baris,6).toString();
        alamatAyah = jTableAyah.getValueAt(baris,7).toString();
        desaAyah = jTableAyah.getValueAt(baris,8).toString();
        kelurahanAyah = jTableAyah.getValueAt(baris,9).toString();
        kecamatanAyah = jTableAyah.getValueAt(baris,10).toString();

        labelAyah.setVisible(true);
    }//GEN-LAST:event_jTableAyahMouseClicked

    private void txtNikAyahKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNikAyahKeyReleased
        // TODO add your handling code here:
        String key = txtNikAyah.getText();
        System.out.println(key);
        if(key!=""){
            cariDataAyah(key);
        }else{
            TampilDataAyah();
        }
    }//GEN-LAST:event_txtNikAyahKeyReleased

    private void txtNikIbuKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNikIbuKeyReleased
        // TODO add your handling code here:
        String key = txtNikIbu.getText();
        System.out.println(key);
        if(key!=""){
            cariDataIbu(key);
        }else{
            TampilDataIbu();
        }
    }//GEN-LAST:event_txtNikIbuKeyReleased

    private void jTableIbuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableIbuMouseClicked
        // TODO add your handling code here:
        int baris = jTableIbu.rowAtPoint(evt.getPoint());
        String nik2 = jTableIbu.getValueAt(baris, 0).toString();
        txtNikIbu.setText(nik2);
        nikIbu = jTableIbu.getValueAt(baris, 0).toString();
        namaIbu = jTableIbu.getValueAt(baris,1).toString();
        jkIbu = jTableIbu.getValueAt(baris,2).toString();
        tgllahirIbu = jTableIbu.getValueAt(baris,3).toString();
        tempatlahirIbu = jTableIbu.getValueAt(baris,4).toString();
        agamaIbu = jTableIbu.getValueAt(baris,5).toString();
        pekerjaanIbu = jTableIbu.getValueAt(baris,6).toString();
        alamatIbu = jTableIbu.getValueAt(baris,7).toString();
        desaIbu = jTableIbu.getValueAt(baris,8).toString();
        kelurahanIbu = jTableIbu.getValueAt(baris,9).toString();
        kecamatanIbu = jTableIbu.getValueAt(baris,10).toString();

        labelIbu.setVisible(true);
    }//GEN-LAST:event_jTableIbuMouseClicked

    private void txtNikPelaporKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNikPelaporKeyReleased
        // TODO add your handling code here:
        String key = txtNikPelapor.getText();
        System.out.println(key);
        if(key!=""){
            cariDataPelapor(key);
        }else{
            TampilDataPelapor();
        }
    }//GEN-LAST:event_txtNikPelaporKeyReleased

    private void jTablePelaporMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTablePelaporMouseClicked
        // TODO add your handling code here:
        int baris = jTablePelapor.rowAtPoint(evt.getPoint());
        String nik2 = jTablePelapor.getValueAt(baris, 0).toString();
        txtNikPelapor.setText(nik2);
        nikPelapor = jTablePelapor.getValueAt(baris, 0).toString();
        namaPelapor = jTablePelapor.getValueAt(baris,1).toString();
        jkPelapor = jTablePelapor.getValueAt(baris,2).toString();
        tgllahirPelapor = jTablePelapor.getValueAt(baris,3).toString();
        tempatlahirPelapor = jTablePelapor.getValueAt(baris,4).toString();
        agamaPelapor = jTablePelapor.getValueAt(baris,5).toString();
        pekerjaanPelapor = jTablePelapor.getValueAt(baris,6).toString();
        alamatPelapor = jTablePelapor.getValueAt(baris,7).toString();
        desaPelapor = jTablePelapor.getValueAt(baris,8).toString();
        kelurahanPelapor = jTablePelapor.getValueAt(baris,9).toString();
        kecamatanPelapor = jTablePelapor.getValueAt(baris,10).toString();

        labelPelapor.setVisible(true);
    }//GEN-LAST:event_jTablePelaporMouseClicked

    private void txtNikSaksiKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNikSaksiKeyReleased
        // TODO add your handling code here:
        String key = txtNikSaksi.getText();
        System.out.println(key);
        if(key!=""){
            cariDataSaksi(key);
        }else{
            TampilDataSaksi();
        }
    }//GEN-LAST:event_txtNikSaksiKeyReleased

    private void jTableSaksiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableSaksiMouseClicked
        // TODO add your handling code here:
        int baris = jTableSaksi.rowAtPoint(evt.getPoint());
        String nik2 = jTableSaksi.getValueAt(baris, 0).toString();
        txtNikSaksi.setText(nik2);
        nikSaksi = jTableSaksi.getValueAt(baris, 0).toString();
        namaSaksi = jTableSaksi.getValueAt(baris,1).toString();
        jkSaksi = jTableSaksi.getValueAt(baris,2).toString();
        tgllahirSaksi = jTableSaksi.getValueAt(baris,3).toString();
        tempatlahirSaksi = jTableSaksi.getValueAt(baris,4).toString();
        agamaSaksi = jTableSaksi.getValueAt(baris,5).toString();
        pekerjaanSaksi = jTableSaksi.getValueAt(baris,6).toString();
        alamatSaksi = jTableSaksi.getValueAt(baris,7).toString();
        desaSaksi = jTableSaksi.getValueAt(baris,8).toString();
        kelurahanSaksi = jTableSaksi.getValueAt(baris,9).toString();
        kecamatanSaksi = jTableSaksi.getValueAt(baris,10).toString();

        labelSaksi.setVisible(true);
    }//GEN-LAST:event_jTableSaksiMouseClicked

    private void btnSimpanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSimpanMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_btnSimpanMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameSuratKematian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameSuratKematian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameSuratKematian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameSuratKematian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameSuratKematian().setVisible(true);
            }
        });
    }

    public void TampilDataJenazah() {
        DftTblModel_data = new DefaultTableModel();
        DftTblModel_data.addColumn("NIK");
        DftTblModel_data.addColumn("NAMA");
        DftTblModel_data.addColumn("JENIS KELAMIN");
        DftTblModel_data.addColumn("TANGGAL LAHIR");
        DftTblModel_data.addColumn("TEMPAT LAHIR");
        DftTblModel_data.addColumn("AGAMA");
        DftTblModel_data.addColumn("PEKERJAAN");
        DftTblModel_data.addColumn("ALAMAT");
        DftTblModel_data.addColumn("DESA");
        DftTblModel_data.addColumn("KELURAHAN");
        DftTblModel_data.addColumn("KECAMATAN");
        jTableJenazah.setModel(DftTblModel_data);
        Connection conn = Koneksi.getConnection();
        try {
            java.sql.Statement stmt = conn.createStatement();
            SQL = "SELECT * FROM data_penduduk";
            java.sql.ResultSet res = stmt.executeQuery(SQL);
            while (res.next()) {
                DftTblModel_data.addRow(new Object[]{
                    res.getString("nik_ktp"),
                    res.getString("nama"),
                    res.getString("jenis_kelamin"),
                    res.getString("tgl_lahir"),
                    res.getString("tempat_lahir"),
                    res.getString("agama"),
                    res.getString("pekerjaan"),
                    res.getString("alamat"),
                    res.getString("dusun_desa"),
                    res.getString("kelurahan"),
                    res.getString("kecamatan")
                });
            }
        } catch (SQLException e) {
            System.out.println(e.getMessage());
        }
    }

    private void cariDataJenazah(String key){
        DftTblModel_data = new DefaultTableModel();
        DftTblModel_data.addColumn("NIK");
        DftTblModel_data.addColumn("NAMA");
        DftTblModel_data.addColumn("JENIS KELAMIN");
        DftTblModel_data.addColumn("TANGGAL LAHIR");
        DftTblModel_data.addColumn("TEMPAT LAHIR");
        DftTblModel_data.addColumn("AGAMA");
        DftTblModel_data.addColumn("PEKERJAAN");
        DftTblModel_data.addColumn("ALAMAT");
        DftTblModel_data.addColumn("DESA");
        DftTblModel_data.addColumn("KELURAHAN");
        DftTblModel_data.addColumn("KECAMATAN");
        jTableJenazah.setModel(DftTblModel_data);
        Connection conn = Koneksi.getConnection();
        try {
            java.sql.Statement stmt = conn.createStatement();
            SQL = "SELECT * FROM data_penduduk WHERE nik_ktp LIKE '%"+key+"%'";
            java.sql.ResultSet res = stmt.executeQuery(SQL);
            while (res.next()) {
                DftTblModel_data.addRow(new Object[]{
                    res.getString("nik_ktp"),
                    res.getString("nama"),
                    res.getString("jenis_kelamin"),
                    res.getString("tgl_lahir"),
                    res.getString("tempat_lahir"),
                    res.getString("agama"),
                    res.getString("pekerjaan"),
                    res.getString("alamat"),
                    res.getString("dusun_desa"),
                    res.getString("kelurahan"),
                    res.getString("kecamatan")
                });
            }
        } catch (SQLException e) {
            System.out.println(e.getMessage());
        }
    }

//data ayah
    public void TampilDataAyah() {
        DftTblModel_data = new DefaultTableModel();
        DftTblModel_data.addColumn("NIK");
        DftTblModel_data.addColumn("NAMA");
        DftTblModel_data.addColumn("JENIS KELAMIN");
        DftTblModel_data.addColumn("TANGGAL LAHIR");
        DftTblModel_data.addColumn("TEMPAT LAHIR");
        DftTblModel_data.addColumn("AGAMA");
        DftTblModel_data.addColumn("PEKERJAAN");
        DftTblModel_data.addColumn("ALAMAT");
        DftTblModel_data.addColumn("DESA");
        DftTblModel_data.addColumn("KELURAHAN");
        DftTblModel_data.addColumn("KECAMATAN");
        jTableAyah.setModel(DftTblModel_data);
        Connection conn = Koneksi.getConnection();
        try {
            java.sql.Statement stmt = conn.createStatement();
            SQL = "SELECT * FROM data_penduduk";
            java.sql.ResultSet res = stmt.executeQuery(SQL);
            while (res.next()) {
                DftTblModel_data.addRow(new Object[]{
                    res.getString("nik_ktp"),
                    res.getString("nama"),
                    res.getString("jenis_kelamin"),
                    res.getString("tgl_lahir"),
                    res.getString("tempat_lahir"),
                    res.getString("agama"),
                    res.getString("pekerjaan"),
                    res.getString("alamat"),
                    res.getString("dusun_desa"),
                    res.getString("kelurahan"),
                    res.getString("kecamatan")
                });
            }
        } catch (SQLException e) {
            System.out.println(e.getMessage());
        }
    }

    private void cariDataAyah(String key){
        DftTblModel_data = new DefaultTableModel();
        DftTblModel_data.addColumn("NIK");
        DftTblModel_data.addColumn("NAMA");
        DftTblModel_data.addColumn("JENIS KELAMIN");
        DftTblModel_data.addColumn("TANGGAL LAHIR");
        DftTblModel_data.addColumn("TEMPAT LAHIR");
        DftTblModel_data.addColumn("AGAMA");
        DftTblModel_data.addColumn("PEKERJAAN");
        DftTblModel_data.addColumn("ALAMAT");
        DftTblModel_data.addColumn("DESA");
        DftTblModel_data.addColumn("KELURAHAN");
        DftTblModel_data.addColumn("KECAMATAN");
        jTableAyah.setModel(DftTblModel_data);
        Connection conn = Koneksi.getConnection();
        try {
            java.sql.Statement stmt = conn.createStatement();
            SQL = "SELECT * FROM data_penduduk WHERE nik_ktp LIKE '%"+key+"%'";
            java.sql.ResultSet res = stmt.executeQuery(SQL);
            while (res.next()) {
                DftTblModel_data.addRow(new Object[]{
                    res.getString("nik_ktp"),
                    res.getString("nama"),
                    res.getString("jenis_kelamin"),
                    res.getString("tgl_lahir"),
                    res.getString("tempat_lahir"),
                    res.getString("agama"),
                    res.getString("pekerjaan"),
                    res.getString("alamat"),
                    res.getString("dusun_desa"),
                    res.getString("kelurahan"),
                    res.getString("kecamatan")
                });
            }
        } catch (SQLException e) {
            System.out.println(e.getMessage());
        }
    }

//identitas ibu
    public void TampilDataIbu() {
        DftTblModel_data = new DefaultTableModel();
        DftTblModel_data.addColumn("NIK");
        DftTblModel_data.addColumn("NAMA");
        DftTblModel_data.addColumn("JENIS KELAMIN");
        DftTblModel_data.addColumn("TANGGAL LAHIR");
        DftTblModel_data.addColumn("TEMPAT LAHIR");
        DftTblModel_data.addColumn("AGAMA");
        DftTblModel_data.addColumn("PEKERJAAN");
        DftTblModel_data.addColumn("ALAMAT");
        DftTblModel_data.addColumn("DESA");
        DftTblModel_data.addColumn("KELURAHAN");
        DftTblModel_data.addColumn("KECAMATAN");
        jTableIbu.setModel(DftTblModel_data);
        Connection conn = Koneksi.getConnection();
        try {
            java.sql.Statement stmt = conn.createStatement();
            SQL = "SELECT * FROM data_penduduk";
            java.sql.ResultSet res = stmt.executeQuery(SQL);
            while (res.next()) {
                DftTblModel_data.addRow(new Object[]{
                    res.getString("nik_ktp"),
                    res.getString("nama"),
                    res.getString("jenis_kelamin"),
                    res.getString("tgl_lahir"),
                    res.getString("tempat_lahir"),
                    res.getString("agama"),
                    res.getString("pekerjaan"),
                    res.getString("alamat"),
                    res.getString("dusun_desa"),
                    res.getString("kelurahan"),
                    res.getString("kecamatan")
                });
            }
        } catch (SQLException e) {
            System.out.println(e.getMessage());
        }
    }

    private void cariDataIbu(String key){
        DftTblModel_data = new DefaultTableModel();
        DftTblModel_data.addColumn("NIK");
        DftTblModel_data.addColumn("NAMA");
        DftTblModel_data.addColumn("JENIS KELAMIN");
        DftTblModel_data.addColumn("TANGGAL LAHIR");
        DftTblModel_data.addColumn("TEMPAT LAHIR");
        DftTblModel_data.addColumn("AGAMA");
        DftTblModel_data.addColumn("PEKERJAAN");
        DftTblModel_data.addColumn("ALAMAT");
        DftTblModel_data.addColumn("DESA");
        DftTblModel_data.addColumn("KELURAHAN");
        DftTblModel_data.addColumn("KECAMATAN");
        jTableIbu.setModel(DftTblModel_data);
        Connection conn = Koneksi.getConnection();
        try {
            java.sql.Statement stmt = conn.createStatement();
            SQL = "SELECT * FROM data_penduduk WHERE nik_ktp LIKE '%"+key+"%'";
            java.sql.ResultSet res = stmt.executeQuery(SQL);
            while (res.next()) {
                DftTblModel_data.addRow(new Object[]{
                    res.getString("nik_ktp"),
                    res.getString("nama"),
                    res.getString("jenis_kelamin"),
                    res.getString("tgl_lahir"),
                    res.getString("tempat_lahir"),
                    res.getString("agama"),
                    res.getString("pekerjaan"),
                    res.getString("alamat"),
                    res.getString("dusun_desa"),
                    res.getString("kelurahan"),
                    res.getString("kecamatan")
                });
            }
        } catch (SQLException e) {
            System.out.println(e.getMessage());
        }
    }

//identitas Pelapor
    public void TampilDataPelapor() {
        DftTblModel_data = new DefaultTableModel();
        DftTblModel_data.addColumn("NIK");
        DftTblModel_data.addColumn("NAMA");
        DftTblModel_data.addColumn("JENIS KELAMIN");
        DftTblModel_data.addColumn("TANGGAL LAHIR");
        DftTblModel_data.addColumn("TEMPAT LAHIR");
        DftTblModel_data.addColumn("AGAMA");
        DftTblModel_data.addColumn("PEKERJAAN");
        DftTblModel_data.addColumn("ALAMAT");
        DftTblModel_data.addColumn("DESA");
        DftTblModel_data.addColumn("KELURAHAN");
        DftTblModel_data.addColumn("KECAMATAN");
        jTablePelapor.setModel(DftTblModel_data);
        Connection conn = Koneksi.getConnection();
        try {
            java.sql.Statement stmt = conn.createStatement();
            SQL = "SELECT * FROM data_penduduk";
            java.sql.ResultSet res = stmt.executeQuery(SQL);
            while (res.next()) {
                DftTblModel_data.addRow(new Object[]{
                    res.getString("nik_ktp"),
                    res.getString("nama"),
                    res.getString("jenis_kelamin"),
                    res.getString("tgl_lahir"),
                    res.getString("tempat_lahir"),
                    res.getString("agama"),
                    res.getString("pekerjaan"),
                    res.getString("alamat"),
                    res.getString("dusun_desa"),
                    res.getString("kelurahan"),
                    res.getString("kecamatan")
                });
            }
        } catch (SQLException e) {
            System.out.println(e.getMessage());
        }
    }

    private void cariDataPelapor(String key){
        DftTblModel_data = new DefaultTableModel();
        DftTblModel_data.addColumn("NIK");
        DftTblModel_data.addColumn("NAMA");
        DftTblModel_data.addColumn("JENIS KELAMIN");
        DftTblModel_data.addColumn("TANGGAL LAHIR");
        DftTblModel_data.addColumn("TEMPAT LAHIR");
        DftTblModel_data.addColumn("AGAMA");
        DftTblModel_data.addColumn("PEKERJAAN");
        DftTblModel_data.addColumn("ALAMAT");
        DftTblModel_data.addColumn("DESA");
        DftTblModel_data.addColumn("KELURAHAN");
        DftTblModel_data.addColumn("KECAMATAN");
        jTablePelapor.setModel(DftTblModel_data);
        Connection conn = Koneksi.getConnection();
        try {
            java.sql.Statement stmt = conn.createStatement();
            SQL = "SELECT * FROM data_penduduk WHERE nik_ktp LIKE '%"+key+"%'";
            java.sql.ResultSet res = stmt.executeQuery(SQL);
            while (res.next()) {
                DftTblModel_data.addRow(new Object[]{
                    res.getString("nik_ktp"),
                    res.getString("nama"),
                    res.getString("jenis_kelamin"),
                    res.getString("tgl_lahir"),
                    res.getString("tempat_lahir"),
                    res.getString("agama"),
                    res.getString("pekerjaan"),
                    res.getString("alamat"),
                    res.getString("dusun_desa"),
                    res.getString("kelurahan"),
                    res.getString("kecamatan")
                });
            }
        } catch (SQLException e) {
            System.out.println(e.getMessage());
        }
    }

//identitas saksi
    public void TampilDataSaksi() {
        DftTblModel_data = new DefaultTableModel();
        DftTblModel_data.addColumn("NIK");
        DftTblModel_data.addColumn("NAMA");
        DftTblModel_data.addColumn("JENIS KELAMIN");
        DftTblModel_data.addColumn("TANGGAL LAHIR");
        DftTblModel_data.addColumn("TEMPAT LAHIR");
        DftTblModel_data.addColumn("AGAMA");
        DftTblModel_data.addColumn("PEKERJAAN");
        DftTblModel_data.addColumn("ALAMAT");
        DftTblModel_data.addColumn("DESA");
        DftTblModel_data.addColumn("KELURAHAN");
        DftTblModel_data.addColumn("KECAMATAN");
        jTableSaksi.setModel(DftTblModel_data);
        Connection conn = Koneksi.getConnection();
        try {
            java.sql.Statement stmt = conn.createStatement();
            SQL = "SELECT * FROM data_penduduk";
            java.sql.ResultSet res = stmt.executeQuery(SQL);
            while (res.next()) {
                DftTblModel_data.addRow(new Object[]{
                    res.getString("nik_ktp"),
                    res.getString("nama"),
                    res.getString("jenis_kelamin"),
                    res.getString("tgl_lahir"),
                    res.getString("tempat_lahir"),
                    res.getString("agama"),
                    res.getString("pekerjaan"),
                    res.getString("alamat"),
                    res.getString("dusun_desa"),
                    res.getString("kelurahan"),
                    res.getString("kecamatan")
                });
            }
        } catch (SQLException e) {
            System.out.println(e.getMessage());
        }
    }

    private void cariDataSaksi(String key){
        DftTblModel_data = new DefaultTableModel();
        DftTblModel_data.addColumn("NIK");
        DftTblModel_data.addColumn("NAMA");
        DftTblModel_data.addColumn("JENIS KELAMIN");
        DftTblModel_data.addColumn("TANGGAL LAHIR");
        DftTblModel_data.addColumn("TEMPAT LAHIR");
        DftTblModel_data.addColumn("AGAMA");
        DftTblModel_data.addColumn("PEKERJAAN");
        DftTblModel_data.addColumn("ALAMAT");
        DftTblModel_data.addColumn("DESA");
        DftTblModel_data.addColumn("KELURAHAN");
        DftTblModel_data.addColumn("KECAMATAN");
        jTableSaksi.setModel(DftTblModel_data);
        Connection conn = Koneksi.getConnection();
        try {
            java.sql.Statement stmt = conn.createStatement();
            SQL = "SELECT * FROM data_penduduk WHERE nik_ktp LIKE '%"+key+"%'";
            java.sql.ResultSet res = stmt.executeQuery(SQL);
            while (res.next()) {
                DftTblModel_data.addRow(new Object[]{
                    res.getString("nik_ktp"),
                    res.getString("nama"),
                    res.getString("jenis_kelamin"),
                    res.getString("tgl_lahir"),
                    res.getString("tempat_lahir"),
                    res.getString("agama"),
                    res.getString("pekerjaan"),
                    res.getString("alamat"),
                    res.getString("dusun_desa"),
                    res.getString("kelurahan"),
                    res.getString("kecamatan")
                });
            }
        } catch (SQLException e) {
            System.out.println(e.getMessage());
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSimpan;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTable jTableAyah;
    private javax.swing.JTable jTableIbu;
    private javax.swing.JTable jTableJenazah;
    private javax.swing.JTable jTablePelapor;
    private javax.swing.JTable jTableSaksi;
    private javax.swing.JLabel labelAyah;
    private javax.swing.JLabel labelIbu;
    private javax.swing.JLabel labelJenazah;
    private javax.swing.JLabel labelPelapor;
    private javax.swing.JLabel labelSaksi;
    private javax.swing.JTextField txtAnak;
    private javax.swing.JComboBox<String> txtMenerangkan;
    private javax.swing.JTextField txtNamaKK;
    private javax.swing.JTextField txtNikAyah;
    private javax.swing.JTextField txtNikIbu;
    private javax.swing.JTextField txtNikJenazah;
    private javax.swing.JTextField txtNikPelapor;
    private javax.swing.JTextField txtNikSaksi;
    private javax.swing.JTextField txtNomorKK;
    private javax.swing.JTextField txtPukul;
    private javax.swing.JComboBox<String> txtSebab;
    private com.toedter.calendar.JDateChooser txtTanggal;
    private javax.swing.JTextField txtTempat;
    // End of variables declaration//GEN-END:variables
}
